import { cookies } from "next/headers"
import { Geist, Geist_Mono } from "next/font/google"
//import jwt from "jsonwebtoken"
import { redirect } from "next/navigation"

import "../globals.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata = {
    title: "CopySure - Authentic Check",
    description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
    const cookieStore = await cookies()
    const email = cookieStore.get("email")
    if (email === undefined || email === null || email === "") {
        redirect("/login")
    }
    // const { data: session, status } = useSession()
    // const cookieStore = cookies()

    // if (status === "authenticated") {
    //     return (
    //         <html lang="en">
    //             <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    //                 Hello yellow
    //                 {children}
    //             </body>
    //         </html>
    //     )
    //     redirect("/dashboard")
    // } else {
    //     redirect("/login")
    // }
    //const token = cookieStore.get("token")

    // if (!token) {
    //     redirect("/login")
    // }

    // try {
    //     //jwt.verify(token.value, process.env.JWT_SECRET_KEY)
    // } catch (error) {
    //     redirect("/login")
    // }
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {children}
            </body>
        </html>
    )
}
