import "../globals.css"
import { Toaster } from "sonner"

export const metadata = {
    title: "CopySure - Authentic Check",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <Toaster richColors />
                {children}
            </body>
        </html>
    )
}
