export const mockExams = [
    {
        id: "1",
        name: "Modern History Exam - HIST 101",
        key: "abc123",
        created: "2024-04-17",
        status: "closed",
        isLocked: true,
        isRestricted: false,
        isMonitored: false,
        actions: { canEdit: true, canView: true, canMonitor: true },
    },
    {
        id: "2",
        name: "Geometry Grid - MATH 302",
        key: "math123",
        created: "2024-04-17",
        status: "closed",
        isLocked: true,
        isRestricted: false,
        isMonitored: false,
        actions: { canEdit: true, canView: true, canMonitor: true },
    },
    {
        id: "3",
        name: "Creative Writing Challenge - ENGL 215",
        key: "eng456",
        created: "2024-04-12",
        status: "open",
        isLocked: false,
        isRestricted: false,
        isMonitored: false,
        actions: { canEdit: true, canView: true, canMonitor: true },
    },
    {
        id: "4",
        name: "Spanish Grammar II",
        key: "span789",
        created: "2024-04-09",
        status: "partial",
        isLocked: false,
        isRestricted: false,
        isMonitored: false,
        actions: { canEdit: true, canView: true, canMonitor: true },
    },
    {
        id: "5",
        name: "Biology Blitz",
        key: "bio101",
        created: "2024-04-02",
        status: "closed",
        isLocked: true,
        isRestricted: false,
        isMonitored: false,
        actions: { canEdit: true, canView: true, canMonitor: true },
    },
    {
        id: "6",
        name: "Algebra - MATH 302",
        key: "alg202",
        created: "2024-04-02",
        status: "closed",
        isLocked: true,
        isRestricted: true,
        isMonitored: true,
        actions: { canEdit: true, canView: true, canMonitor: true },
    },
    {
        id: "7",
        name: "Chemistry Challenges 2.0",
        key: "chem300",
        created: "2024-03-07",
        status: "closed",
        isLocked: false,
        isRestricted: false,
        isMonitored: false,
        actions: { canEdit: true, canView: true, canMonitor: true },
    },
    {
        id: "8",
        name: "World History II - HIST 102",
        key: "hist222",
        created: "2024-02-12",
        status: "open",
        isLocked: false,
        isRestricted: false,
        isMonitored: false,
        actions: { canEdit: true, canView: true, canMonitor: true },
    },
    {
        id: "9",
        name: "Classic literature test - ENGL 202",
        key: "lit999",
        created: "2024-02-06",
        status: "closed",
        isLocked: true,
        isRestricted: true,
        isMonitored: false,
        actions: { canEdit: true, canView: true, canMonitor: true },
    },
]
